version: '3'
services:
  app:
    container_name: long-file-processing
    restart: always
    build: .
    ports:
      - '80:2312'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.4.4
    ports:
      - '27017:27017'